use_frameworks!

platform :ios, '10.0'

target 'GZCodeCoverageKit_Example' do
  pod 'GZCodeCoverageKit', :path => '../'

  target 'GZCodeCoverageKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
